# Generated by Django 5.2.7 on 2026-05-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_four_digits',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='logo',
        ),
    ]
