# Generated by Django 5.2.7 on 2025-10-19 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('transaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Транзакція',
                'verbose_name_plural': 'Транзакції',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bank_statements/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Очікує'), ('PROCESSING', 'В обробці'), ('COMPLETED', 'Завершено'), ('FAILED', 'Помилка')], default='PENDING', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Завантаження виписки',
                'verbose_name_plural': 'Завантаження виписок',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('INCOME', 'Дохід'), ('EXPENSE', 'Витрата')], max_length=7)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.category')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
    ]
