# Generated by Django 5.2.7 on 2025-12-27 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_category_unique_together_category_is_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionupload',
            name='source_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.transactionupload'),
        ),
    ]
