# Generated by Django 5.2.7 on 2026-05-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_source_transaction_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
